on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/renovate.json'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.github/renovate.json'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      env:
        BUILD_CONFIG: "nosb"
      with:
        esp_idf_version: v5.4.1
        target: ${{ matrix.platform }}
    - name: Upload artifact bin
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: build/${{ matrix.platform }}_*.bin
