name: "Firmware Build"

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/renovate.json'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.github/renovate.json'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Cache Managed Components
      uses: actions/cache@v4
      with:
          path: 'managed_components'
          key: ${{ runner.os }}-managed_components-${{ hashFiles("dependencies.lock.${{ matrix.platform }}") }}
    - name: Build with ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4.1
        target: ${{ matrix.platform }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: build/${{ matrix.platform }}_*.bin
