on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4
        target: ${{ matrix.platform }}
    - name: Rename file bin
      shell: bash
      run: cp build/hello_world.bin ${{ matrix.platform }}-hello_world.bin
    - name: Upload artifact bin
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-firmware-${{ matrix.platform }}
        path: ${{ matrix.platform }}-hello_world.bin

  sign:
    runs-on: ubuntu-latest
    needs: build
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: unsigned-firmware-${{ matrix.platform }}
    - name: Load SIGNING_KEY
      run: echo "$SIGNING_KEY" > ./signing_key.pem
    - name: Sign firmware
      uses: espressif/esp-idf-ci-action@main
      with:
        esp_idf_version: v5.4
        command: espsecure.py sign_data -v2 --keyfile signing_key.pem --output ${{ matrix.platform }}-hello_world.signed.bin ${{ matrix.platform }}-hello_world.bin
    - name: Remove SIGNING_KEY
      run: rm -f ./signing_key.pem
    - name: Upload artifact bin
      uses: actions/upload-artifact@v4
      with:
        name: unsigned-firmware-${{ matrix.platform }}
        path: ${{ matrix.platform }}-hello_world.signed.bin
