ame: "Firmware Build"

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths-ignore:
      - '*.md'
      - '.github/renovate.json'
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.github/renovate.json'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    env:
      DEPENDENCIES_LOCK: dependencies.lock.${{ matrix.platform }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Restore Managed Components from Cache
      id: cache-managed-components
      uses: actions/cache/restore@v4
      with:
          path: managed_components
          key: ${{ runner.os }}-${{ hashFiles(env.DEPENDENCIES_LOCK) }}
    - name: Build with ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4.1
        target: ${{ matrix.platform }}
    - name: Cache Managed Components
      uses: actions/cache/save@v4
      with:
        path: managed_components
        key: ${{ steps.cache-managed-components.outputs.cache-primary-key }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: build/${{ matrix.platform }}_*.bin
