on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Load SIGNING_KEY
      run: echo "${{ secrets.SIGNING_KEY }}" > ./secure_boot_signing_key.pem
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      env:
        SDKCONFIG_DEFAULTS: "sdkconfig.defaults;sdkconfig.release.defaults"
      with:
        esp_idf_version: v5.4.1
        target: ${{ matrix.platform }}
    - name: Remove SIGNING_KEY
      run: rm -f ./secure_boot_signing_key.pem
    - name: Upload artifact bin
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: build/${{ matrix.platform }}_*.bin

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v4
      with:
        pattern: '*'
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: "**/*.bin"
        generate_release_notes: true
