on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call-workflow-build:
    uses: ./.github/workflows/build.yml

  sign:
    runs-on: ubuntu-latest
    needs: call-workflow-build
    env:
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
    strategy:
      matrix:
        platform: [esp32, esp32s2, esp32s3]
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.platform }}-firmware-unsigned
    - name: Load SIGNING_KEY
      run: echo "$SIGNING_KEY" > ./signing_key.pem
    - name: Sign firmware
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.4.1
        target: ${{ matrix.platform }}
        command: espsecure.py sign_data -v2 --keyfile signing_key.pem --output ${{ matrix.platform }}-hello_world.signed.bin ${{ matrix.platform }}-hello_world.bin
    - name: Remove SIGNING_KEY
      run: rm -f ./signing_key.pem
    - name: Upload artifact bin
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-firmware-signed
        path: ${{ matrix.platform }}-hello_world.signed.bin
