name: "Semantic PR Validation"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  validate-semantic-pr:
    if: github.event.pull_request.draft == false
    name: Validate PR Title for Semantic Compliance
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
